name: stacktion
description: runs the pre publish checks and if fine, creates a release

outputs:
  success:
    description: whether success or not
  errors:
    description: a line seperated list of errors

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        path: '${{ github.action_path }}/stack_repo' 
    - uses: actions/setup-ruby@v1
    - name: install dependencies and run validator
      shell: bash
      run: |
        cd ${{ github.action_path }}
        gem install bundler
        bundle update --bundler
        bundle install
        ruby validator.rb
