name: stacktion
description: runs the pre publish checks and if fine, creates a release

outputs:
  success:
    description: whether success or not
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: echo "${{ github.action_path }}"
      shell: bash 
    - name: install dependencies and run validator
      shell: bash
      run: |
        echo "${{ env.GITHUB_WORKSPACE }}"
        cd ${{ github.action_path }}
        gem install bundler
        bundle update --bundler
        bundle install
    - id: bruh
      name: install dependencies and run validator
      shell: bash
      run: |
        ruby ${{ github.action_path }}/validator.rb ${{ github.action_path }}

    - run: echo ${{ steps.bruh.outputs.success }}
      shell: bash